### ISSUE TITLE
UI - [Very short description]

### ISSUE THREAD

**Issue by KermitsRevenge** [BitSoftwareCo/BSC-Applications#4]
## Location
Where is the UI bug at

So, no clue exactly where I'm supposed to add suggestions- but! I think it would be super cool really entirely helpful if you created some kind of password manager.

**Comment by BitSoftwareCo** [comment]
I would also enjoy a password manager app. I will inform the development team and get back to you with what they said.

***Thank you for your feedback! Your input is always valued at Stone Software***
This repo is currently archived and we highly recommend you submit feature requests [here](https://github.com/Stone-Software/BSC-Applications)

**Comment by BitSoftwareCo** [comment]
I informed the development team and they said it will becoming in future major release.
